#!/data/data/com.termux/files/usr/bin/bash

# Copyright (c) 2022-2022
# Romeo Delta <rudidev89@gmail.com>

source /storage/emulated/0/rudidev89/sys/function.sh

# create your script here.

case ${1} in
	create) bash ${sbinpath}/generator $*; exit;;
	*)exit 1
esac

